Fixes LiteCore issue 684 (mailbox race condition)
couchbaselabs/BLIP-Cpp pull request #13
Opened 2019-02-01 03:30 UTC by borrrden

Until now a race has existed between when the event count is decremented after a call to enqueue and the logic of enqueue being executed.  This meant there was the potential for an actor to get into a false busy state and behave badly.  In particular a replicator would never inform its delegate that it had stopped.

2019-02-01 03:31 UTC, borrrden commented
@snej I tested this on both Mac and Windows with the full set of CBL tests (and had to make quite a few corrections to ThreadedMailbox) so I'm pretty confident that this is the end of the issue, but could you add a sanity check?

2019-02-01 17:05 UTC, snej requested changes

2019-02-01 17:05 UTC, snej commented on src/util/GCDMailbox.cc
> +    void GCDMailbox::beforeEvent() {
Decrementing `_eventCount` before calling the Actor method seems wrong. It changes the interpretation of that variable while the Actor is running, and externally it makes it look as though the Actor is idle before it finishes running the event.

2019-02-01 17:05 UTC, snej commented on src/util/ThreadedMailbox.cc
> +            --_delayedEventCount;
Same comment — this seems like the wrong time to decrement. Why not at the start of afterEvent()?

2019-02-01 21:45 UTC, borrrden commented on src/util/GCDMailbox.cc
> +    void GCDMailbox::beforeEvent() {
OH!  Interesting.  I think I'd gotten convinced that computeActivityLevel got called in the callback somehow and not during _actor->afterEvent().  I'll fix this back up accordingly.

2019-02-01 23:25 UTC, borrrden commented
Alright updated!

2019-02-01 23:36 UTC, snej requested changes

2019-02-01 23:36 UTC, snej commented on src/util/GCDMailbox.cc
> +        _actor->afterEvent();
This still decrements `_eventCount` before `computeStatus` runs, so it would now have to compare it against 0 instead of 1.

2019-02-01 23:36 UTC, snej commented on src/util/ThreadedMailbox.cc
> +            --_delayedEventCount;
My mistake — I should have said "at the _end_ of afterEvent", i.e. after `_actor->afterEvent()` is called.

2019-02-02 00:23 UTC, snej commented on src/util/ThreadedMailbox.cc
> +            --_delayedEventCount;
Never mind -- I now agree this is correct!

2019-02-02 00:33 UTC, merged